# Generated by Django 5.0.3 on 2024-03-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, db_column='FirstName', max_length=50)),
                ('LastName', models.CharField(blank=True, db_column='LastName', max_length=50)),
                ('Nickname', models.CharField(blank=True, db_column='Nickname', max_length=50)),
                ('Email', models.EmailField(db_column='Email', help_text='напишите mail!', max_length=254)),
                ('FaceImage', models.ImageField(db_column='FaceImage', upload_to='faceImage')),
                ('IdUser', models.ForeignKey(db_column='IdUser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'author',
                'db_table': 'AuthorNews',
                'ordering': ['Email'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='Title', help_text=' напишите название новости! ', max_length=100)),
                ('TheNews', models.TextField(db_column='TheNews', help_text=' напишите текст новости! ')),
                ('TimePublished', models.DateTimeField(auto_now=True, db_column='published')),
                ('image', models.ImageField(help_text=' добавте картинки! ', upload_to='NewsImage')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
            options={
                'verbose_name': 'News',
                'db_table': 'News',
            },
        ),
    ]
